### ISSUE TITLE
启动pity.py报错

### ISSUE THREAD

**Issue by yijia0404** [wuranxu/pity#90]
E:\github\pity>python pity.py
2023-01-28 15:50:12,082 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-01-28 15:50:12,082 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-01-28 15:50:12,082 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-01-28 15:50:12,098 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-01-28 15:50:12,102 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-01-28 15:50:12,102 INFO sqlalchemy.engine.Engine [raw sql] {}
Traceback (most recent call last):
  File "D:\Program Files\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\github\pity\pity.py", line 10, in <module>
    uvicorn.run("main:pity", host=Config.SERVER_HOST, port=Config.SERVER_PORT, reload=False, forwarded_allow_ips="*")
  File "D:\Program Files\Python311\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Program Files\Python311\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "D:\Program Files\Python311\Lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\github\pity\main.py", line 14, in <module>
    from app.core.ws_connection_manager import ws_manage
  File "E:\github\pity\app\core\ws_connection_manager.py", line 7, in <module>
    from app.crud.notification.NotificationDao import PityNotificationDao
  File "E:\github\pity\app\crud\__init__.py", line 21, in <module>
    from app.models import Base, async_session, async_engine
  File "E:\github\pity\app\models\__init__.py", line 21, in <module>
    create_database()
  File "E:\github\pity\app\models\__init__.py", line 15, in create_database
    conn.execute("CREATE DATABASE IF NOT EXISTS pity default character set utf8mb4 collate utf8mb4_unicode_ci")
  File "D:\Program Files\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'CREATE DATABASE IF NOT EXISTS pity default character set utf8mb4 collate utf8mb4_unicode_ci'

**Comment by yijia0404** [comment]
不知道是不是mysql配置的问题，有成功启动服务的同学，可以提供win下mysql的my.ini的配置信息

**Comment by wuranxu** [comment]
> 不知道是不是mysql配置的问题，有成功启动服务的同学，可以提供win下mysql的my.ini的配置信息

mysql建议在8.0版本以上，5.x的版本没做很好的支持。

**Comment by yijia0404** [comment]
# MySQL config
MYSQL_HOST="127.0.0.1"
MYSQL_PORT=3306
MYSQL_USER="root"
MYSQL_PWD="123456"
DBNAME="pity"

# Redis config
REDIS_ON=True
REDIS_HOST="127.0.0.1"
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD="123456"

# Github token
CLIENT_ID="c46c7ae33442d13498cd"
SECRET_KEY="6cb53ad7d135bb91a07f2deb7203d484741f1644"

# Server port
SERVER_PORT=7777

# Mock server
MOCK_ON=False
PROXY_ON=False
PROXY_PORT=7778

# ETCD
ETCD_ENDPOINT=127.0.0.1:2379



这是我dev.env的配置文件，应该也没错吧。
我安装的也是mysql8.0的版本，但是还是上面的报错。
看报错，是不是没有生成连接数据库的对象，所以没办法执行语句？

太难了。QAQ！

**Comment by wuranxu** [comment]
解决了吗？我这边Python3.10是ok的，我看你的版本是3.11，没有测试过 看起来是创建pity数据库的时候sql语句报错了，大概是找不到对应的connection对象，你可以先手动创建下pity

**Comment by yijia0404** [comment]
> 

我自己手动建立pity'的数据库，还是不行。
    engine = create_engine('mysql+mysqlconnector://{}:{}@{}:{}'.format(
        Config.MYSQL_USER, Config.MYSQL_PWD, Config.MYSQL_HOST, Config.MYSQL_PORT), echo=True)
应该是生成操作数据库对象失败了

**Comment by yijia0404** [comment]
我看项目的SQLAlchemy模块是1.4.11，但是我装的是2.0.0。
2.0.0版本的好像有些功能不可用了。

**Comment by yijia0404** [comment]
换成1.4.11后，报错没有了

**Comment by wuranxu** [comment]
> 换成1.4.11后，报错没有了

好的，sqlalchemy版本可能我是 ~=1.4.1 导致的，那我固定一下，2.0之前是beta版本，后续我也考虑升级一下。感谢反馈~
